/**
 * Azure Neural TTS — synthesis přes REST API.
 * Output: audio/mpeg (MP3 24kHz).
 *
 * Docs: https://learn.microsoft.com/azure/ai-services/speech-service/rest-text-to-speech
 *
 * AI Act compliance (čl. 50, effective 2026-08-02):
 *   Každý výstup má perceivable disclosure — úvodní audio chime ~0.5s
 *   s textem "Generated by VoiceDub" v jazyce TTS voice. Layered s ID3 metadata.
 *   Enterprise tier může disable přes `disableWatermark: true` (customer bears
 *   responsibility per čl. 50 písm. g — underwritten v kontraktu).
 */

// Disclosure text per locale — TTS namluví v cílovém jazyce, aby to znělo přirozeně.
const WATERMARK_TEXT = {
  'cs-CZ': 'Tato nahrávka byla vygenerována umělou inteligencí.',
  'sk-SK': 'Táto nahrávka bola vygenerovaná umelou inteligenciou.',
  'pl-PL': 'To nagranie zostało wygenerowane przez sztuczną inteligencję.',
  'hu-HU': 'Ez a felvétel mesterséges intelligenciával készült.',
  'en-US': 'This recording was generated by AI.',
};

export async function synthesizeSSML(text, voiceId, { key, region, disableWatermark = false, speed = 0, pitch = 0 } = {}) {
  if (!key) throw new Error('AZURE_SPEECH_KEY missing');
  if (!region) throw new Error('AZURE_SPEECH_REGION missing');

  const locale = voiceId.split('-').slice(0, 2).join('-'); // cs-CZ
  const watermark = disableWatermark ? '' : buildWatermark(locale, voiceId);
  const rateAttr = `${speed >= 0 ? '+' : ''}${speed}%`;
  const pitchAttr = `${pitch >= 0 ? '+' : ''}${pitch}%`;
  const ssml = `<speak version="1.0" xml:lang="${locale}" xmlns="http://www.w3.org/2001/10/synthesis">
  <voice name="${voiceId}">
    ${watermark}
    <prosody rate="${rateAttr}" pitch="${pitchAttr}">${escapeXml(text)}</prosody>
  </voice>
</speak>`;

  const url = `https://${region}.tts.speech.microsoft.com/cognitiveservices/v1`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'Ocp-Apim-Subscription-Key': key,
      'Content-Type': 'application/ssml+xml',
      'X-Microsoft-OutputFormat': 'audio-24khz-48kbitrate-mono-mp3',
      'User-Agent': 'VoiceDub-API/0.1',
    },
    body: ssml,
  });
  if (!res.ok) throw new Error(`Azure TTS ${res.status}: ${(await res.text()).slice(0, 300)}`);
  return res.arrayBuffer();
}

function escapeXml(s) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Vytvoří AI Act watermark SSML fragment — krátká věta (~0.5s) před hlavním obsahem,
 * s rate +15 % (rychlejší) a volume -20 % (tišší), aby to bylo vnímatelné, ale nerušilo.
 * Následuje 300ms pauza, pak normální obsah.
 */
function buildWatermark(locale, voiceId) {
  const text = WATERMARK_TEXT[locale] || WATERMARK_TEXT['en-US'];
  return `<prosody rate="+15%" volume="-20%">${escapeXml(text)}</prosody><break time="300ms"/>`;
}
