import { test } from 'node:test';
import assert from 'node:assert/strict';

// Test jen SSML building helper — skutečné HTTP volání vyžaduje AZURE_SPEECH_KEY a
// pokryjeme ho integration testem. Cílem je zaručit AI Act čl. 50 watermark kontrakt.
//
// Protože `buildWatermark` není exportován, testujeme přes `synthesizeSSML`
// a monkeypatchujeme global fetch tak, aby vrátil ArrayBuffer a zachytil SSML.

test('watermark: default ON — SSML obsahuje disclosure text v locale', async () => {
  let capturedBody;
  const origFetch = globalThis.fetch;
  globalThis.fetch = async (url, opts) => {
    capturedBody = opts.body;
    return { ok: true, arrayBuffer: async () => new ArrayBuffer(0) };
  };

  const mod = await import('./azure-tts.js');
  await mod.synthesizeSSML('Ahoj světe', 'cs-CZ-VlastaNeural', {
    key: 'fake', region: 'westeurope',
  });

  globalThis.fetch = origFetch;

  assert.match(capturedBody, /Tato nahrávka byla vygenerována umělou inteligencí/);
  assert.match(capturedBody, /<break time="300ms"\/>/);
  assert.match(capturedBody, /Ahoj světe/);
});

test('watermark: disableWatermark=true — disclosure NENÍ v SSML', async () => {
  let capturedBody;
  const origFetch = globalThis.fetch;
  globalThis.fetch = async (url, opts) => {
    capturedBody = opts.body;
    return { ok: true, arrayBuffer: async () => new ArrayBuffer(0) };
  };

  const mod = await import('./azure-tts.js');
  await mod.synthesizeSSML('Hello world', 'en-US-JennyNeural', {
    key: 'fake', region: 'eastus',
    disableWatermark: true,
  });

  globalThis.fetch = origFetch;

  assert.doesNotMatch(capturedBody, /Generated by AI|by VoiceDub|vygenerována/);
  assert.match(capturedBody, /Hello world/);
});

test('watermark: polský locale má lokalizovaný disclosure', async () => {
  let capturedBody;
  const origFetch = globalThis.fetch;
  globalThis.fetch = async (url, opts) => {
    capturedBody = opts.body;
    return { ok: true, arrayBuffer: async () => new ArrayBuffer(0) };
  };

  const mod = await import('./azure-tts.js');
  await mod.synthesizeSSML('Dzień dobry', 'pl-PL-ZofiaNeural', {
    key: 'fake', region: 'westeurope',
  });

  globalThis.fetch = origFetch;

  assert.match(capturedBody, /zostało wygenerowane przez sztuczną inteligencję/);
});
